### ISSUE TITLE
rawJSON support for replacers

### ISSUE THREAD

**Issue by CJxD** [Kikobeats/json-stringify-deterministic#21]
I've run into an issue after switching from the standard JSON.stringify() function to this library.

Up to and including v1.0.12 and using Node v22.10.2, the library seems to serialize [rawJSON](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/rawJSON) as an object whereas the standard JSON.stringify() treats it as a quoteless string as expected.

Is it possible to add support for this?

Here's a test example:

```
import stringify from 'json-stable-stringify';

const data = {
  someText: "hello",
  someFloat: 1.0,
  someInt: 1,
};

function replacer(this: stringify.Node, field: stringify.Key, value: unknown): unknown {
  if (field === 'someFloat') {
    // @ts-ignore node types doesn't recognize rawJSON yet (v22.10.2)
    return JSON.rawJSON(value);
  }
  return value;
}

const strBody = stringify(data, { replacer });

console.log(strBody);
```

This should return

```
{"someFloat":1.0,"someInt":1,"someText":"hello"}
```

but instead I get

```
{"someFloat":{"rawJSON":"1"},"someInt":1,"someText":"hello"}
```

**Comment by Kikobeats** [comment]
Passing a custom stringify function is already supported.

Try this:

```
const strBody = stringify(data, { replacer,  stringify: JSON.rawJSON });
```

🙂
