### ISSUE TITLE
Option to sort arrays

### ISSUE THREAD

**Issue by domoritz** [Kikobeats/json-stringify-deterministic#4]
It would be nice to have an option to sort arrays (and maybe even remove duplicates?). This comes in handy if arrays are expected to be sets.

**Comment by Kikobeats** [comment]
Thanks for the tip.

I created a package for do that: https://github.com/Kikobeats/sort-keys-recursive

how we can integrate in this project?

**Comment by domoritz** [comment]
Excellent. I think since one can just chain the calls (`stringify (sortKeysRecursive(foo))`), it works fine. Thanks for the pointer!

**Comment by Kikobeats** [comment]
Good point; I'm going to add a tip in the documentation. Thanks!
